name: notify_app
description: Notification-based 1-line chat app
publish_to: "none"

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  firebase_core: ^2.24.2
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.8
  firebase_messaging: ^14.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true